### ISSUE TITLE
The Typography images are huge

### ISSUE THREAD

**Issue by ig-ealbert** [IgniteUI/indigo-design-docfx#102]
https://staging.infragistics.local/indigo-docfx/style/typography.html
The image covers the right-side content.
If possible it should not do that.
Please fix in English and Japanese.

**Comment by StefanIvanov** [comment]
i can redo them to be narrower, shall I?

**Comment by ig-ealbert** [comment]
This isn't critical for the launch.  I'm writing a status email now.  If you want to fix them, go ahead, but we can update them at a later date after the first release.

**Comment by StefanIvanov** [comment]
Fixed with #103

**Comment by ig-ealbert** [comment]
From what I see this is not fixed.  But also not critical.

**Comment by ig-ealbert** [comment]
@StefanIvanov I still see it covering up the right side of the screen.  I have tried Ctrl + F5 but nothing changes.  Do I need to do something else to make the image size correctly?
![image](https://user-images.githubusercontent.com/8162597/41917288-04a03b8a-7928-11e8-81e3-b164d896a6bd.png)

**Comment by StefanIvanov** [comment]
It looks like your browser loads the retina image on a non-retina screen

**Comment by ig-ealbert** [comment]
@tiliev My browser zoom is set to 100%.  I even zoomed out (80%) and I still get the larger image.  How do I check the "custom OS scaling"?  I have Windows 7 and as far as I know, I haven't changed the scaling settings.

**Comment by tiliev** [comment]
@ig-ealbert, this setting looks like this on Win 7:

![](http://www.lawfirmsoftware.com/support/images/dpi_windows7/540px-How_to_Change_DPI_Size_in_Windows_7-009.png)

**Comment by tiliev** [comment]
@ig-ealbert, I'll spend some time investigating this and will get back to you.

**Comment by StefanIvanov** [comment]
Now that we have an image width limit of 830px I have reduced the size of images with pull request #180
